apiVersion: v1 # Versión de la API de Kubernetes.
kind: PersistentVolumeClaim # Indica que este manifiesto define un PersistentVolumeClaim.
metadata:
  name: mysql-pvc # Nombre único para este PersistentVolumeClaim.
spec:
  storageClassName: manual # Debe coincidir con la 'storageClassName' del PV que se quiere reclamar.
  accessModes:
    - ReadWriteOnce # Modo de acceso solicitado (lectura-escritura por un único nodo).
  resources:
    requests:
      storage: 10Gi # Cantidad de almacenamiento solicitada (debe ser igual o menor a la capacidad del PV).
